version: "3.8"

services:
  gateway:
    build: .
    container_name: flask-gateway
    ports:
      - "5004:5004"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gateway.rule=PathPrefix(`/`)"
      - "traefik.http.services.gateway.loadbalancer.server.port=5004"
    networks:
      - traefik

networks:
  traefik:
    external: true
